name: lan_sharing
description: "A flutter package for quickly create lan sharing functionality."
version: 0.1.0
homepage: https://github.com/ddao33/lan_sharing

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
